data<-read.table("C:\\Users\\rohitk\\Desktop\\COURSERA R\\exdata_data_household_power_consumption\\household_power_consumption.txt",stringsAsFactors= FALSE,sep = ";",na.strings = "?", header = TRUE)
data$Date<- as.Date(data$Date,format = "%d/%m/%Y")
library(chron)
data$Time<- chron(times=data$Time)
library(dplyr)
plotdata<-select(data,Global_active_power,Date,Time)
plotoftwodays<-filter(plotdata, Date == "2007-02-01" | Date == "2007-02-02")
newtime<-paste(as.character(plotoftwodays$Date),as.character(plotoftwodays$Time))
newtime<-strptime(newtime, format="%Y-%m-%d %H:%M:%S")
png(filename = "Plot2_GAP_load.png")
plot(x=newtime, y=plotoftwodays$Global_active_power, type="l",xlab ="",ylab = "Global Active Power (kilowatts)") 
dev.off()
