data<-read.table("C:\\Users\\rohitk\\Desktop\\COURSERA R\\exdata_data_household_power_consumption\\household_power_consumption.txt",stringsAsFactors= FALSE,sep = ";",na.strings = "?", header = TRUE)
data$Date<- as.Date(data$Date,format = "%d/%m/%Y")
library(chron)
data$Time<- chron(times=data$Time)
library(dplyr)
plotdata<-select(data,Global_active_power,Date,Time,Sub_metering_1,Sub_metering_2,Sub_metering_3,Voltage,Global_reactive_power)
plotoftwodays<-filter(plotdata, Date == "2007-02-01" | Date == "2007-02-02")
newtime<-paste(as.character(plotoftwodays$Date),as.character(plotoftwodays$Time))
newtime<-strptime(newtime, format="%Y-%m-%d %H:%M:%S")
png(filename = "Plot4_2by2.png")
par(mfrow=c(2,2),mar = c(6, 6, 4, 0), oma = c(0, 0, 0, 1))
plot(x=newtime, y=plotoftwodays$Global_active_power, type="l",xlab ="",ylab = "Global Active Power") 
plot(x=newtime, y=plotoftwodays$Voltage,type="l",xlab ="datetime",ylab = "Voltage")
plot(x=newtime, y=plotoftwodays$Sub_metering_1,type = "l",xlab="",ylab = "Energy sub metering")
points(x=newtime, y=plotoftwodays$Sub_metering_2,type = "l", col = "dark green")
points(x=newtime, y=plotoftwodays$Sub_metering_3,type = "l", col = "blue")
legend("topright",lty=1,box.lty = 0,inset=0.01,cex=0.9,legend=c("sub_metering_1","sub_metering_2","sub_metering_3"),col = c("black","dark green", "blue"))
plot(x=newtime, y=plotoftwodays$Global_reactive_power,type="l",xlab ="datetime",ylab = "Global_reactive_power")
dev.off()
