data<-read.table("C:\\Users\\rohitk\\Desktop\\COURSERA R\\exdata_data_household_power_consumption\\household_power_consumption.txt",stringsAsFactors= FALSE,sep = ";",na.strings = "?", header = TRUE)
data$Date<- as.Date(data$Date,format = "%d/%m/%Y")
library(chron)
data$Time<- chron(times=data$Time)
library(dplyr)
plotdata<-select(data,Date,Time,Sub_metering_1,Sub_metering_2,Sub_metering_3)
plotoftwodays<-filter(plotdata, Date == "2007-02-01" | Date == "2007-02-02")
newtime<-paste(as.character(plotoftwodays$Date),as.character(plotoftwodays$Time))
newtime<-strptime(newtime, format="%Y-%m-%d %H:%M:%S")
png(filename = "Plot3_Submetering.png")
plot(x=newtime, y=plotoftwodays$Sub_metering_1,type = "l",xlab="",ylab = "Energy sub metering")
points(x=newtime, y=plotoftwodays$Sub_metering_2,type = "l", col = "dark green")
points(x=newtime, y=plotoftwodays$Sub_metering_3,type = "l", col = "blue")
legend("topright",lty=1,legend=c("sub_metering_1","sub_metering_2","sub_metering_3"),col = c("black","dark green", "blue"))
dev.off()
